# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

inhibit_all_warnings!

use_frameworks!

def exarappiPods
 # Pods for ExamenRappi
    pod 'Alamofire', '4.8.2'
    pod 'ObjectMapper', '3.4.2'
    pod 'RealmSwift', '3.15.0'
    pod 'ObjectMapper+Realm', '0.6'
    pod 'AlamofireImage', '3.5.2'
    pod 'RxSwift', '4.5.0'
    pod 'RxCocoa', '4.5.0'
    pod 'RxGesture', '2.2.0'
    pod 'SwiftMessages', '5.0.1'
    pod 'NVActivityIndicatorView','4.4.0'
    pod 'IQKeyboardManagerSwift', '6.3.0'
    pod 'lottie-ios', '2.5.3'
    pod 'YoutubePlayer-in-WKWebView', '0.2.5'
    pod 'SwiftyGif', '4.2.0'
 end


  target 'ExamenRappi' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  	exarappiPods
  end
 

  target 'ExamenRappiTests' do
    inherit! :search_paths
    # Pods for testing
    exarappiPods
  end

  target 'ExamenRappiUITests' do
    inherit! :search_paths
    # Pods for testing
    exarappiPods
  end


